
tasks:
  - init: npm install && npm run build && npm install -g eslint' # runs during prebuild
    command: npm run dev


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview



vscode:
  extensions:
    - gengjiawen.vscode-npm-dependency